# Generated by Django 4.2.5 on 2024-06-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='categories',
        ),
    ]
